/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import './stencil.core';




export namespace Components {

  interface BfGrid {
    'images': string[];
    'token': string;
  }
  interface BfGridAttributes extends StencilHTMLAttributes {
    'images'?: string[];
    'onImageSelected'?: (event: CustomEvent) => void;
    'token'?: string;
  }

  interface BfImageGrid {
    'images': string[];
    'token': string;
  }
  interface BfImageGridAttributes extends StencilHTMLAttributes {
    'images'?: string[];
    'token'?: string;
  }

  interface BfImageList {
    'height': number;
    'images': string[];
    'token': string;
    'width': number;
  }
  interface BfImageListAttributes extends StencilHTMLAttributes {
    'height'?: number;
    'images'?: string[];
    'onImageSelected'?: (event: CustomEvent) => void;
    'token'?: string;
    'width'?: number;
  }

  interface BfImg {
    'height': string;
    'operation': string;
    'quality': number;
    'token': string;
    'url': string;
    'width': string;
  }
  interface BfImgAttributes extends StencilHTMLAttributes {
    'height'?: string;
    'operation'?: string;
    'quality'?: number;
    'token'?: string;
    'url'?: string;
    'width'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'BfGrid': Components.BfGrid;
    'BfImageGrid': Components.BfImageGrid;
    'BfImageList': Components.BfImageList;
    'BfImg': Components.BfImg;
  }

  interface StencilIntrinsicElements {
    'bf-grid': Components.BfGridAttributes;
    'bf-image-grid': Components.BfImageGridAttributes;
    'bf-image-list': Components.BfImageListAttributes;
    'bf-img': Components.BfImgAttributes;
  }


  interface HTMLBfGridElement extends Components.BfGrid, HTMLStencilElement {}
  var HTMLBfGridElement: {
    prototype: HTMLBfGridElement;
    new (): HTMLBfGridElement;
  };

  interface HTMLBfImageGridElement extends Components.BfImageGrid, HTMLStencilElement {}
  var HTMLBfImageGridElement: {
    prototype: HTMLBfImageGridElement;
    new (): HTMLBfImageGridElement;
  };

  interface HTMLBfImageListElement extends Components.BfImageList, HTMLStencilElement {}
  var HTMLBfImageListElement: {
    prototype: HTMLBfImageListElement;
    new (): HTMLBfImageListElement;
  };

  interface HTMLBfImgElement extends Components.BfImg, HTMLStencilElement {}
  var HTMLBfImgElement: {
    prototype: HTMLBfImgElement;
    new (): HTMLBfImgElement;
  };

  interface HTMLElementTagNameMap {
    'bf-grid': HTMLBfGridElement
    'bf-image-grid': HTMLBfImageGridElement
    'bf-image-list': HTMLBfImageListElement
    'bf-img': HTMLBfImgElement
  }

  interface ElementTagNameMap {
    'bf-grid': HTMLBfGridElement;
    'bf-image-grid': HTMLBfImageGridElement;
    'bf-image-list': HTMLBfImageListElement;
    'bf-img': HTMLBfImgElement;
  }


}
